Develop
raheebwa/mint-signup-form pull request #2
Opened 2019-09-20 20:48 UTC by Tripple-A

2019-09-21 18:27 UTC, Forison reviewed
# pull request under review by Addo

2019-09-21 20:07 UTC, Forison commented on index.html
> +    <header id="header">
Use class instead of id 🙂

2019-09-21 20:07 UTC, Forison commented on index.html
> +    <main id="main">
Use class instead of id 🙂

2019-09-21 20:07 UTC, Forison commented on index.html
> +        <div id="signup-box">
Use class instead of id 🙂 more

2019-09-21 20:14 UTC, Forison requested changes
Good Job @AHEEBA && AJIBADE, 🙂
I love the way you organized your files. Your project looks good. 👌
However, technically, your project violates some CSS best practices.

**[REQUIRED]**
Do not use id as selectors in your project(Id selectors have priority over other kinds of selectors. This can make it harder to add new rules using less specific selectors, leading to specificity wars), use class instead. read on the best practices [here](https://speckyboy.com/good-bad-css-practices/). 

**[OPTIONAL]**
> I saw you use ``` p ``` as wraps for you form element thus ```<label> and <input>``` I suggest you use ```<div>```. I understand they are block elements part ```div``` is more semantic and mostly use for this purpose
## Kindly make changes and submit them for review again. You are almost there.🙂
#### Happy coding 🙂🙂

2019-09-23 13:39 UTC, SunnyAsar approved these changes
# Hello @Tripple-A  and @raheebwa 👋 
Nicely done Guys, Let's move to the next project 🚀 
## You May Pass 👍

2019-09-23 15:07 UTC, merged